name: build
on: push
jobs:
  build:
    name: ${{ matrix.project }}
    runs-on: windows-2022

    strategy:
      matrix:
        project: [foo_spider_monkey_panel]

    steps:
    - uses: actions/checkout@v4

    - name: Set up MSBuild
      uses: microsoft/setup-msbuild@v2

    - name: Build
      run: |
        msbuild src\${{ matrix.project }}.sln

    - name: Upload
      uses: actions/upload-artifact@v4
      with:
        name: ${{ matrix.project }}-${{ github.ref_name }}
        path: component
